### ISSUE TITLE
The vibration effect is lacking on MIUI 

### ISSUE THREAD

**Issue by lateautumn233** [UtsavBalar1231/kernel_xiaomi_sm8250#12]
Some of the vibration effects are missing on the 
Miui13 

For example: taskallclean 

log: https://pastebin.com/53qFVkN5

![Screenshot_2022-04-11-17-18-53-229_com miui home](https://user-images.githubusercontent.com/63851402/162708995-64581917-505c-474c-9bc9-f7ad3b804bf9.png)

You can test it in this interface 

![Screenshot_2022-04-11-17-23-12-159_com android settings](https://user-images.githubusercontent.com/63851402/162708630-c17adee0-de74-4040-b2c0-970a0fbd94bc.png)

Thanks.

**Comment by UtsavBalar1231** [comment]
Works on alioth miui 13

**Comment by lateautumn233** [comment]
> Works on alioth miui 13
I'm sorry. I'm apollo

**Comment by lateautumn233** [comment]
> Works on alioth miui 13

I'm sorry. I'm apollo

**Comment by lateautumn233** [comment]
Probably because of the file name?

**Comment by lateautumn233** [comment]
> Probably because of the file name?

Path:/vendor/firmware/vibrator_firmware_aidl/
https://pastebin.com/JakyEJ63

**Comment by ff19** [comment]
that’s your problem .i have built  it for apollo ，and there is no problem on vibration like this

**Comment by UtsavBalar1231** [comment]
Try picking this commit https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6
@lateautumn233

**Comment by lateautumn233** [comment]
> Try picking this commit [e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6) @lateautumn233

He doesn't work

**Comment by F-19-F** [comment]
> > Try picking this commit [e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6) @lateautumn233
> 
> He doesn't work

try https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12 ？

**Comment by lateautumn233** [comment]
> > > 尝试选择这个提交[e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6)  @lateautumn233
> > 
> > 
> > 他不工作
> 
> 试试https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12？



> > > Try picking this commit [e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6) @lateautumn233
> > 
> > 
> > He doesn't work
> 
> try https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12 ？

doesn't work 
  0.780308] aw8697_read_chipid unsupported device revision (0x4)

**Comment by F-19-F** [comment]
> > > > 尝试选择这个提交[e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6)  @lateautumn233
> > > 
> > > 
> > > 他不工作
> > 
> > 
> > 试试[https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12？](https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12%EF%BC%9F)
> 
> > > > Try picking this commit [e43b304](https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/commit/e43b304d259459000b108abad1d7a29f754e9ba6) @lateautumn233
> > > 
> > > 
> > > He doesn't work
> > 
> > 
> > try https://github.com/ff19/kernel_xiaomi_sm8250/releases/tag/22.04.12 ？
> 
> doesn't work 0.780308] aw8697_read_chipid unsupported device revision (0x4)

This kernel works on my device with MIUI13.0.4 satble build.

**Comment by F-19-F** [comment]
[    0.621698] aw8697 driver version v1.1.3
[    0.621704] aw8697_i2c_init success
[    0.623453] aw8697_i2c_probe enter
[    0.623474] aw8697_haptic 2-005a: aw8697_parse_dt: reset gpio provi
ded ok
[    0.623479] aw8697_haptic 2-005a: aw8697_parse_dt: irq gpio provided ok.
![Screenshot_2022-04-14-13-07-03-880_com android settings](https://user-images.githubusercontent.com/58457605/163317585-bb5a5891-fcf4-4c97-ae71-dae470fea9f7.jpg)

**Comment by lateautumn233** [comment]
> [ 0.621698] aw8697 driver version v1.1.3 [ 0.621704] aw8697_i2c_init success [ 0.623453] aw8697_i2c_probe enter [ 0.623474] aw8697_haptic 2-005a: aw8697_parse_dt: reset gpio provi ded ok [ 0.623479] aw8697_haptic 2-005a: aw8697_parse_dt: irq gpio provided ok. ![Screenshot_2022-04-14-13-07-03-880_com android settings](https://user-images.githubusercontent.com/58457605/163317585-bb5a5891-fcf4-4c97-ae71-dae470fea9f7.jpg)

aw8697_read_chipid
What's this yours

**Comment by F-19-F** [comment]
![Uploading Screenshot_2022-04-14-13-13-11-954_com.termux.jpg…]()

**Comment by ff19** [comment]
![Screenshot_2022-04-14-13-13-11-954_com termux](https://user-images.githubusercontent.com/80933556/163318385-fd84d8f5-4914-43be-8a76-ade5c0e0bf20.jpg)

**Comment by lateautumn233** [comment]
> ![Screenshot_2022-04-14-13-13-11-954_com termux](https://user-images.githubusercontent.com/80933556/163318385-fd84d8f5-4914-43be-8a76-ade5c0e0bf20.jpg)

That's the problem.
I'm aw86907

**Comment by lateautumn233** [comment]
Can not solve, can only wait for Xiaomi to update the source code
