### ISSUE TITLE
Help wanted build error..

### ISSUE THREAD

**Issue by Saikatsaha1996** [UtsavBalar1231/kernel_xiaomi_sm8250#22]
Can you help please ? 
![IMG_20220815_030910](https://user-images.githubusercontent.com/72664192/184555964-4732dbf4-02c5-4ac0-ab17-4efad9789b37.jpg)

**Comment by UtsavBalar1231** [comment]
Please do not open compilation help as an issue here.

**Comment by Saikatsaha1996** [comment]
Vmlinux. Version genaration failed with error

![Screenshot_2022-08-15-10-03-05-549_tech ula](https://user-images.githubusercontent.com/72664192/184580634-ae3d1ced-6ebf-42bc-bb66-4642d99b9149.jpg)

**Comment by Saikatsaha1996** [comment]
I just wanted to know any patches available for this kernel? ..

I am not edited any configuration.. b lineage-19.1 useing los-toolchain (lineage os) ubuntu 22.04 pc desktop..


![IMG_20220815_182023](https://user-images.githubusercontent.com/72664192/184639055-ce784aaf-8830-426d-a2c3-c7de58548748.jpg)
