### ISSUE TITLE
[udfps] Is udfps will get functional supported on sm8250 devices ?

### ISSUE THREAD

**Issue by stuartore** [UtsavBalar1231/kernel_xiaomi_sm8250#34]
as title.
#### device: `psyche`
+ Global HBM  - `DISPPARAM_HBM_ON`
Works. faces a high light problem after unlocking
+ Local HBM - `DISPPARAM_HBM_FOD_ON`
Seems not work

**Comment by nanoandrew4** [comment]
Same happens with umi, this doesn't happen with [this kernel](https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_lmi/tree/lineage-20)

**Comment by stuartore** [comment]
> Same happens with umi, this doesn't happen with [this kernel](https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_lmi/tree/lineage-20)

### Summary
It keeps high level of brightness without recovering the brightness level after pressing udfps area. By the way, [this kernel](https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_lmi/tree/lineage-20) do not drive udfps sensor light through setting `DISPPARAM_HBM_ON` mode to it's path `DISPPARAM_PATH` currently.

I wonder this commit https://github.com/GrettoRosella/android_kernel_xiaomi_sm8250/commit/ce143e943bc14f3440b9b96304299297eabf5fa8 maybe give some help.

### Details
So I re-write `dsi_panel_set_fod_hbm()` which will be used in `sde_connector.c` with another function that contains `dsi_panel_set_fod_hbm()`. I think I could use `dsi_panel_get_brightness()` before setting DISPPARAM HBM mode while recovering by  `dsi_panel_set_backlight()` after HBM mode off.
```
void sde_connector_update_fod_hbm(struct drm_connector *connector)
{
........
dsi_panel_set_fod_hbm(display->panel, status);
......
}
```
But I'm not so good at c language nor a kernel pro so I failed. Now the problem still happens. Anyone could offer some ideas for the kernel development
