### ISSUE TITLE
lineageos build krnel error

### ISSUE THREAD

**Issue by lingchenma** [UtsavBalar1231/kernel_xiaomi_sm8250#46]
`make kernel`

out/target/product/elish/clean_steps.mk was modified, regenerating...
Adding CUSTOM_LOCALES [ast_ES gd_GB cy_GB fur_IT] to PRODUCT_LOCALES [en_US en_US af_ZA am_ET ar_EG ar_XB as_IN az_AZ be_BY bg_BG bn_BD bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_AU en_CA en_GB en_IN en_XA es_ES es_US et_EE eu_ES fa_IR fi_FI fr_CA fr_FR gl_ES gu_IN hi_IN hr_HR hu_HU hy_AM in_ID is_IS it_IT iw_IL ja_JP ka_GE kk_KZ km_KH kn_IN ko_KR ky_KG lo_LA lt_LT lv_LV mk_MK ml_IN mn_MN mr_IN ms_MY my_MM nb_NO ne_NP nl_NL or_IN pa_IN pl_PL pt_BR pt_PT ro_RO ru_RU si_LK sk_SK sl_SI sq_AL sr_Latn_RS sr_RS sv_SE sw_TZ ta_IN te_IN th_TH tl_PH tr_TR uk_UA ur_PK uz_UZ vi_VN zh_CN zh_HK zh_TW zu_ZA en_XC]
out/soong/Android-lineage_elish.mk was modified, regenerating...
[100% 10/10] initializing legacy Make module parser ...
Adding CUSTOM_LOCALES [ast_ES gd_GB cy_GB fur_IT] to PRODUCT_LOCALES [en_US en_US af_ZA am_ET ar_EG ar_XB as_IN az_AZ be_BY bg_BG bn_BD bs_BA ca_ES cs_CZ da_DK de_DE el_GR en_AU en_CA en_GB en_IN en_XA es_ES es_US et_EE eu_ES fa_IR fi_FI fr_CA fr_FR gl_ES gu_IN hi_IN hr_HR hu_HU hy_AM in_ID is_IS it_IT iw_IL ja_JP ka_GE kk_KZ km_KH kn_IN ko_KR ky_KG lo_LA lt_LT lv_LV mk_MK ml_IN mn_MN mr_IN ms_MY my_MM nb_NO ne_NP nl_NL or_IN pa_IN pl_PL pt_BR pt_PT ro_RO ru_RU si_LK sk_SK sl_SI sq_AL sr_Latn_RS sr_RS sv_SE sw_TZ ta_IN te_IN th_TH tl_PH tr_TR uk_UA ur_PK uz_UZ vi_VN zh_CN zh_HK zh_TW zu_ZA en_XC]
[100% 162/162] writing legacy Make module rules ...
out/target/product/elish/obj/CONFIG/kati_packaging/dist.mk was modified, regenerating...
FAILED: ninja: unknown target 'kernel', did you mean 'kern.o'?
23:41:18 ninja failed with: exit status 1

#### failed to build some targets (07:53 (mm:ss)) ####

Which flag do I need to use to configure the kernel name? In which file do I configure it?

**Comment by chaptsand** [comment]
Do you want to compile the kernel separately? 
Perhaps you need to execute the command:
```
make bootimage
```

**Comment by lingchenma** [comment]
> Do you want to compile the kernel separately? Perhaps you need to execute the command:
> 
> ```
> make bootimage
> ```

No, there is still an error.

**Comment by lingchenma** [comment]
I did need to execute make bootimage because I used precompiled
