### ISSUE TITLE
Alioth's color profile is inconsistent on 90Hz

### ISSUE THREAD

**Issue by peterbetos** [UtsavBalar1231/kernel_xiaomi_sm8250#6]
When comparing the color profile of 60Hz and 120Hz for alioth versus 90Hz, the contrast looks are different.

**Comment by UtsavBalar1231** [comment]
That's why i already did this
https://github.com/UtsavBalar1231/devicetree/commit/9c5eaa19d53b42b2563b40a5b63a7bf71b61d5f9

**Comment by peterbetos** [comment]
No chance to revisit 90Hz again though? Will wait for the official to release it first then. Thanks.

Edit: Also raised the issue on the official repo. Maybe they'll check?
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/2321

**Comment by peterbetos** [comment]
@UtsavBalar1231 Is this kernel btw supporting adaptive 60Hz-120Hz switch?
