### ISSUE TITLE
Camera anomaly 

### ISSUE THREAD

**Issue by lateautumn233** [UtsavBalar1231/kernel_xiaomi_sm8250#8]
![Screenshot_2022-03-08-11-04-55-332_com android camera](https://user-images.githubusercontent.com/63851402/157266744-b2f28712-f8a3-4e86-9cf0-f5756a4dee16.jpg)

log:https://netcut.cn/1ftl1sitb

device: apollo

**Comment by UtsavBalar1231** [comment]
Can you use https://katb.in to paste your logs

**Comment by lateautumn233** [comment]
> 您可以使用https://katb.in粘贴您的日志吗

https://katb.in/ofopesagewu

**Comment by lateautumn233** [comment]
cas: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cmi-r-oss/techpack/camera-cas

Other:
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/psyche-r-oss/techpack/camera-dxo

You may need to re-import from here ?

**Comment by lateautumn233** [comment]
It worked properly after I checked out to the official 

https://github.com/lateautumn233/android_kernel_xiaomi_sm8250open/commit/c36b13a8adc5d1311545d6552372ca4fa8f8a2c0

Thanks

**Comment by gotenksIN** [comment]
try with https://github.com/gotenksIN/kernel_xiaomi_sm8250/commit/9a0b86c6d482d9a0e5c94afbe9c2fdffe6b2d43c

**Comment by chaptsand** [comment]
> try with [gotenksIN/kernel_xiaomi_sm8250@9a0b86c](https://github.com/gotenksIN/kernel_xiaomi_sm8250/commit/9a0b86c6d482d9a0e5c94afbe9c2fdffe6b2d43c)

won't work on umi,cam dead too

**Comment by lateautumn233** [comment]
> try with [gotenksIN/kernel_xiaomi_sm8250@9a0b86c](https://github.com/gotenksIN/kernel_xiaomi_sm8250/commit/9a0b86c6d482d9a0e5c94afbe9c2fdffe6b2d43c)

Thank you. He's working fine
